---
version: 2
updates:
    - package-ecosystem: "pip"
      directory: "/"
      target-branch: "develop"
      schedule:
          interval: "weekly"
          day: "saturday"
          time: "09:00"
          timezone: "Europe/Moscow"
      labels:
          - "dependencies"
