[tool.black]
line-length = 100
target_version = ["py39"]
include = '\.pyi?$'
exclude = '((\.eggs|\.git|\.venv)|foo.py)'

[tool.isort]
profile = "black"
line_length = 100

[tool.pyright]

[tool.pylint.format]
max-line-length = 100

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
plugins = "pydantic.mypy"
exclude = '\.venv'

[tool.pydocstyle]
convention = "numpy"
